### ISSUE TITLE
Export an Aragon compatible distribution file 

### ISSUE THREAD

**Issue by 0xNuggan** [CommonsBuild/tec-rewards#13]
Instead of disperse.app, export a file which can be fed into the Aragon "Transactions" app for token distributions

**Comment by 0xNuggan** [comment]
Hey @divine-comedian , where can I find an a template of how this export should look like? The Aragon webapp never finishes loading to me..

**Comment by divine-comedian** [comment]
Dropped into 1hive to see if they can provide the CSV format we need. Here's where the app repo lives JFYI 

https://github.com/1Hive/transactions-app
couldn't find anything helpful in the readme

**Comment by divine-comedian** [comment]
Okay @0xNuggan got a response, super simple format is 

{recipient address}, (amount), (Token Symbol)

i.e 


0x826976d7C600d45FB8287CA1d7c76FC8eb732030 | 5 | TestHNY
-- | -- | --
0x81443887E6Aef75de940B7244783f896B1c034Ca | 5 | TestHNY
0x320c338BCF70bAAaE26e96201C33B48105Bc62C2 | 5 | TestHNY

can literally be copy pasted from this format in a spreadsheet into the Transactions app and it autofills! pretty neat

**Comment by 0xNuggan** [comment]
yeah, that's neat. how does it find the token address, though?

**Comment by divine-comedian** [comment]
> yeah, that's neat. how does it find the token address, though?

It just goes by the token symbol that shows up in the finance app - this could get confusing if there are two tokens with the same symbol

**Comment by 0xNuggan** [comment]
Addressed in #30 and #28 . LMK if that format works for you
