### ISSUE TITLE
Clean up results in the praise rating distribution

### ISSUE THREAD

**Issue by 0xNuggan** [CommonsBuild/tec-rewards#19]
Right now it shows numbers which aren't included in the rating scale because of duplicates are scored. Show only the values [ 0, 1, 3, 5, 8, 13, 21, 34, 55, 89, 144 ]. 
Keep in mind to completely remove those duplicates from data to avoid pollution in the cases where the duplicate score weighting is the same as an allowed number (f.ex. 13 -> 1; 34 -> 3).

**Comment by tree-pi** [comment]
all duplicates removed in the ``praiseDist_test.ipynb``. the output should look normal now.

**Comment by 0xNuggan** [comment]
Are you sure we should remove it from the whole praise_by_quantifier table, instead of just explicitly omitting it when making the graph? There are probably instances where an overview of the quantifier data including duplicates is relevant...
