### ISSUE TITLE
fix formatting of `final_praise_token_allocation.csv`

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/tec-rewards#49]
reviewing some of the data in this file it looks like usernames with spaces and emojis are not being handled well in the CSV file. perhaps this is a problem with RAD but the output files are kept in this repo. @0xNuggan care to take a look?

![image](https://user-images.githubusercontent.com/67759413/169829115-d625fe94-d087-410d-819f-6ea89f56d054.png)
---
![image](https://user-images.githubusercontent.com/67759413/169829477-bb91db98-fcf3-403f-a27b-6704a7dfb74e.png)

**Comment by 0xNuggan** [comment]
That's actually in the settings of the program you are using to open the file... it's interpreting spaces as column separators. 
 
As a reference, GitHub's native visualization doesn't do it, and everything looks alright: 
https://github.com/CommonsBuild/tec-rewards/blob/main/distribution_rounds/round-3/distribution_results/raw_csv_exports/final_praise_token_allocation.csv

I don't know what you use, but LibreOffice always has a popup where you can check/uncheck what to use as separator when importing data.
