### ISSUE TITLE
export praise outliers sheet to CSV

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/tec-rewards#6]
It would be awesome for our review sessions to be able to export the praise outliers data into a CSV file - this makes it much easier for everyone to review the info! 

while we're at it, are there any other useful tables we can export to CSV in the RAD dashboard?

**Comment by 0xNuggan** [comment]
Just added an extra download link at the bottom :)

I can't think of anything else right now which we should export... But it's something to keep look out for during the review sessions
